### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BrandonHall6518** [DaveDuck321/SmashIt#3] opened 2018-03-27 18:16 UTC
I tried to use the compiled version and the bots join but it won't answer its like there just their but won't do anything. Do I have to have them join before the game starts or does it even matter?

**Comment by lectrician1** [comment] 2018-03-28 00:03
Can you please edit your response with proper grammar so that we can actually answer it? Also be more specific on “compiled version”.

**Comment by BrandonHall6518** [comment] 2018-03-28 00:09
The version I used 
is  https://www.mediafire.com/file/z957oji4cmo506p/app-release.apk My problems is that when I type in the game pin and it goes to the answer page, the bots join but it doesn't actually answer with the bots. It will say all 75 bots are joined but when it comes time to answer it doesn't. Now I was wondering if it mattered that I had the bots join in mid game or not. I tried a bunch of other versions of this app but now seem to be working. Even changing smashing mode or # or bots doesn't seem to help.

**Comment by DaveDuck321** [comment] 2018-04-04 01:38
Sorry to hear about this,
Please provide more details so I can fix your issue, was sort of kahoot game was this, did the bots appear on kahoot's website itself and does the app itself say they answered even when they're not?

**Comment by BrandonHall6518** [comment] 2018-04-05 01:30
It was the classic mode and the bots appeared on the kahoots website and yes the app itself says they answered but they arnt actually answering.

**Comment by DaveDuck321** [comment] 2018-05-27 02:17
After testing this, I have been unable to reproduce the error. Closing issue.

**Closed by DaveDuck321** 2018-05-27 02:17 UTC
