### ISSUE TITLE
Broken again :/

### ISSUE THREAD

**Issue by NeonNinjaCat** [DaveDuck321/SmashIt#7] opened 2019-07-27 08:55 UTC
It's broken just as last time :/

**Comment by NeonNinjaCat** [comment] 2019-08-16 01:41
.

**Comment by DaveDuck321** [comment] 2019-08-17 22:20
K, I'll look into it.
Can you post the debug log output?

**Comment by DaveDuck321** [comment] 2019-08-18 00:31
Ok, I've looked into it a bit and fixed the login process so the bots can join.
However, kahoot has made other changes such as introducing a captcha step, depending on how this is implemented it could make bots much more complex. As it is, without a relatively large rewrite the smashers will be kicked from the game after a few seconds.

It's probably worth fixing the classic mode, this will only be a few lines rather than a complete rewrite.

**Comment by NeonNinjaCat** [comment] 2019-08-18 03:29
damn I knew this day would come.

**Comment by ZeevoX** [comment] 2019-08-20 10:17
I've submitted a pull request (#8) in which, in my testing, the bots work and they weren't kicked from the game either. Your mileage may vary, of course, if Kahoot! has added potential additional verification steps.

**Comment by DaveDuck321** [comment] 2019-08-20 17:15
@ZeevoX I've merged your PR, the answering code works again. However, this demonstrates a pretty interesting issue: whats happening is the bots are getting kicked after sitting in the initial lobby for 20 seconds... Once the game actually starts this isn't an issue and the bots dont get kicked after any amount of time.
See if you can reproduce this, it might be region specific, I've been able to reproduce it on my Android 9 OnePlus 3T and an Android 10 emulator.

**Comment by DaveDuck321** [comment] 2019-08-20 18:18
Ok, I've found and fixed the issue. It seems the bots were getting kicked due to Kahoot removing the /meta/subscribe system - this caused the/meta/connect messages to behave incorrectly. Bots can now stay in the lobby indefinitely.

I was worried about the new captcha step but it seems like this doesn't do anything yet.

**Closed by DaveDuck321** 2019-08-20 18:18 UTC
